### ISSUE TITLE
Data driven results are incorrect

### ISSUE THREAD

**Issue by alexrait** [GHPReporter/Ghpr.MSTest.Examples#1]
Let's say I have
[DataRow(1,2)]
[DataRow(2,3)]

It will show the results for the last attribute twice.

**Comment by elv1s42** [comment]
Hi @alexrait !

Can you please copy here full code of the test, I'll try to reproduce the issue and fix it. 
Also please attach `.trx` file with test results if you have one.

Thank you

**Comment by elv1s42** [comment]
Also can you please confirm you are using MSTest V2 ?

**Comment by alexrait** [comment]
Yes, I am using MSTest V2

The trx is OK.

Here is what I see:

My test looks like this:

![image](https://user-images.githubusercontent.com/7493506/45621533-66a25280-ba89-11e8-89fd-29b285c25eac.png)

![image](https://user-images.githubusercontent.com/7493506/45621550-73bf4180-ba89-11e8-8a87-9cb94d0a4335.png)


[report_20180917T1444224580.zip](https://github.com/GHPReporter/Ghpr.MSTest.Examples/files/2388419/report_20180917T1444224580.zip)

**Comment by elv1s42** [comment]
Cool, thank you very much @alexrait 
I've created a separate issue under MSTestV2 repository. 
Will close this issue together with that one

**Comment by elv1s42** [comment]
Changes are implemented here: https://github.com/GHPReporter/Ghpr.MSTestV2/issues/1
I'll include the changes in the nest release.
